# This file configures the behavior of Replit

# The command that is executed when the run button is clicked.
run = "bash start.sh"

# The default file opened in the editor.
entrypoint = "job_apply_gui.py"

# Specifies which packages or dependencies are needed
[packager]
language = "python3"

[languages.python3]
pattern = "**/*.py"

[languages.python3.languageServer]
start = ["pylsp"]

[env]
PYTHONPATH = "${PYTHONPATH}:${REPL_HOME}"
PYTHONUNBUFFERED = "1"

# Enable the package manager
[packager.features]
packageSearch = true
guessImports = true

# Configures the nix channel
[nix]
channel = "stable-22_11"
